services:
  # 1. Database (Existing)
  db:
    image: mysql:8.0
    container_name: thumbnail_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # 2. Local Azure Storage (Azurite) - NEW
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: thumbnail_azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
    command:
      - azurite
      - --blobHost
      - 0.0.0.0
      - --queueHost
      - 0.0.0.0
      - --location
      - /data
      - --loose
      - --skipApiVersionCheck
    volumes:
      - azurite_data:/data
 
  azurite-init:
    image: mcr.microsoft.com/azure-cli
    container_name: thumbnail_azurite_init
    depends_on:
      - azurite
    command: >
      sh -c "
      echo 'Waiting for Azurite to launch...' &&
      sleep 5 &&
      echo 'Setting CORS for Blob...' &&
      az storage cors add --services b --origins '*' --methods GET POST PUT OPTIONS DELETE --allowed-headers '*' --exposed-headers '*' --max-age 3600 --connection-string 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;' &&
      echo 'Setting CORS for Queue...' &&
      az storage cors add --services q --origins '*' --methods GET POST PUT OPTIONS DELETE --allowed-headers '*' --exposed-headers '*' --max-age 3600 --connection-string 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=http://azurite:10001/devstoreaccount1;' &&
      echo 'Azurite configured successfully.'
      "

  redis:
    image: redis:6
    container_name: thumbnail_redis
    ports:
      - "6379:6379"

  # 3. Backend (Django) - UPDATED
  backend:
    build: ./backend
    container_name: thumbnail_be

    # For Deployment
    # command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      azurite:
        condition: service_started
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_HOST=db
      - MYSQL_PORT=3306

      - DEBUG=${DEBUG}
      - DJANGO_SECRET_KEY=${SECRET_KEY}

      - AZURE_CONNECTION_STRING=${AZURITE_CONNECTION_STRING}
        # Dev
    command: python manage.py runserver 0.0.0.0:8000


  # 4. Worker (Python + FFmpeg) - NEW
  worker:
    build: ./backend
    container_name: thumbnail_worker

    volumes:
      - ./backend:/app
      # If the worker needs to write to DB, share DB logic or use API
    depends_on:
      azurite:
        condition: service_started
      db:
        condition: service_healthy
      redis:
        condition: service_started

    command: ["python", "-m", "celery", "-A", "config", "worker", "-l", "info"]
    
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - DJANGO_SECRET_KEY=${SECRET_KEY}
      # Same Connection String as Backend
      - AZURE_HOST=${AZURITE_HOST}
      - AZURE_CONNECTION_STRING=${AZURITE_CONNECTION_STRING}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  


volumes:
  db_data:
  azurite_data: # Persist simulated Azure data